### ISSUE TITLE
Explore Dota 2 workshop tool on new updates and create todo list for all systems

### ISSUE THREAD

**Issue by kritth** [kritth/Unname-Project#1]
Explore the limitation of the current engine to further analyse what needs to be hard-coded and what can derive from current implementation.

Create issue to track progress of each system

Checklist:
- [x] Damage and armor balancing #3
- [x] Leveling system (EXP table and level limitation) #6
- [x] Legacy Class list #5
- [x] Legacy Quest list #11
- [x] Legacy Item list #8
- [x] Legacy Map list #7
- [x] Legacy Shop list #2
- [x] Legacy NPC list #69
- [x] Legacy Normal Monster list #70
- [x] Legacy Dungeon Monster list #71
- [x] Legacy Dungeon Boss list #72
- [x] Map splitting #15
- [x] Stat system #73
- [x] Team shifting #82
- [x] Save/Load system #74
- [x] Respawn point #14
- [x] Spawning system #12
- [x] Questing system #4
- [x] Custom NPC system #75
- [x] Class change system #76
- [x] Economy system #10
- [x] Inventory/Backpack system #77
- [x] Item system #9
- [x] PVP system #13
- [x] Random Loot generator system #78
- [x] Fishing System #83
- [x] UI Listing #79
- [x] Sea travel system (optional) #80
- [x] Talent system (optional: perhaps for balancing later on) #81
