### ISSUE TITLE
[REQUIRED][Class] Tracker

### ISSUE THREAD

**Issue by kritth** [kritth/Unname-Project#38]
## Content
- [ ] Model
- [ ] Hero card
- [ ] Tooltip
- [ ] VFX for all abilities
- [ ] Class change requirement
  - [ ] Talk to NPC from previous job quest
  - [ ] Talk to Naisha near entrance of Mountain Dungeon
  - [ ] Kill 20 Centaurs inside Mountain Dungeon
  - [ ] Talk to Naisha again
- [ ] Start at level 99
## Backend
- [ ] Abilities implementation
*** TBD
