### ISSUE TITLE
[REQUIRED] Class master checklist

### ISSUE THREAD

**Issue by kritth** [kritth/Unname-Project#5]
Completion of following classes:
## Male route
- [x] Novice #16
### Swordman route
- [x] Swordman #17
- [x] Knight #25
- [x] Crusader (3-1) #33
- [x] Avenger (4-1) #49
- [x] Imperial Knight (3-2) #34
- [x] Champion (4-2) #50
### Initiate route
- [x] Initiate #18
- [x] Mage #26
- [x] Wizard (3-1) #35
- [x] White Wizard (4-1) #51
- [x] Sage (3-2) #36
- [x] Arch Sage (4-2) #52
### Thief route
- [x] Thief #19
- [x] Rogue #28
- [x] Assassin (3-1) #39
- [x] Phantom Assassin (4-1) #55
- [x] Stalker (3-2) #40
- [x] Master Stalker (4-2) #56
### Acolyte route
- [x] Acolyte (same skills with female) #20 
- [x] Cleric (same skills with female) #30
- [x] Priest #43
- [x] Hierophant #59
### Witch Hunter route
- [x] Witch hunter #21
- [x] Slayer #31
- [x] Witcher (3-1) #45
- [x] Professional Witcher (4-1) #61
- [x] Inquisitor (3-2) #46
- [x] Grand Inquisitor (4-2) #62
### Druid route
- [x] Druid #22
- [x] Arch Druid #32
- [x] Shapeshifter (3-1) #47
- [x] Runemaster (4-1) #63
- [x] Shaman (3-2) #48
- [x] Summoner (4-2) #64
## Female route
- [x] Novice #16
### Archer route
- [x] Archer #23
- [x] Hunter #27
- [x] Marksman (3-1) #37
- [x] Sniper (4-1) #53
- [x] Tracker (3-2) #38
- [x] Monster Hunter (4-2) #54
### Acolyte route
- [x] Acolyte (same skills with male) #20
- [x] Cleric (same skills with male) #30
- [x] Matriarch #44
- [x] Prophetess #60
### Templar route
- [x] Templar #24
- [x] Arch Templar #29
- [x] Dark Templar (3-1) #41
- [x] Dark Arch Templar (4-1) #57
- [x] High Templar (3-2) #42
- [x] Grand Templar (4-2) #58

**Comment by kritth** [comment]
Complete creating template for all classes. Closing.

**Comment by kritth** [comment]
Reopen this to keep track of the class completion itself
